trigger:
  branches:
    include:
    - master
  paths:
    include:
    - /
  batch: True
name: $(date:yyyyMMdd)$(rev:.r)
resources:
  repositories:
  - repository: self
    type: git
    ref: master
jobs:
- job: Phase_1
  displayName: Agent job 1
  timeoutInMinutes: 0
  pool:
    vmImage: ubuntu-20.04
  steps:
  - checkout: self
  - task: DotNetCoreCLI@2
    displayName: dotnet publish
    inputs:
      command: publish
      arguments: -r linux-x64
  - task: AzureRmWebAppDeployment@4
    displayName: 'Azure App Service Deploy: dcic'
    inputs:
      ConnectedServiceName: 19cc94ef-d6aa-47d7-bc19-bf8c25c0c5b9
      WebAppKind: webAppLinux
      WebAppName: dcic
      DeployToSlotOrASEFlag: true
      ResourceGroupName: rg1
      RuntimeStack: DOTNETCORE|3.1
      StartupCommand: dotnet exec CicdApp.dll
...
